<?php

namespace ITDoors\HaccpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    /**
     * Returns data for backup
     *
     * @return array
     */
    public function getBackupData()
    {
        return $this->createQueryBuilder('obj')
            ->select('obj.id as id')
            ->addSelect('obj.name as name')
            ->getQuery()
            ->getArrayResult();
    }
}
