<?php

namespace ITDoors\HaccpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContourRepository extends EntityRepository
{
    /**
     * Find contours by ids
     *
     * @param int[] $ids
     *
     * @return Contour[]
     */
    public function findByIds($ids)
    {
        return $this->createQueryBuilder('c')
            ->where('c.id in (:ids)')
            ->setParameter(':ids', $ids)
            ->getQuery()
            ->getResult();
    }

    /**
     * Returns data for backup
     *
     * @return array
     */
    public function getBackupData()
    {
        return $this->createQueryBuilder('obj')
            ->select('obj.id as id')
            ->addSelect('obj.name as name')
            ->addSelect('obj.color as color')
            ->addSelect('obj.serviceId as service_id')
            ->addSelect('obj.slug as slug')
            ->addSelect('obj.level as level')
            ->getQuery()
            ->getArrayResult();
    }
}
