<?php

namespace ITDoors\HaccpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends EntityRepository
{
    /**
     * Returns query for show
     *
     * @param int[] $ids
     *
     * @return Query
     */
    public function getForShowQuery($ids)
    {
        return $this->createQueryBuilder('p')
            ->select('p.id as id')
            ->addSelect('p.imageSrc as imageSrc')
            ->addSelect('p.imageWidth as imageWidth')
            ->addSelect('p.imageHeight as imageHeight')
            ->addSelect('p.type as type')
            ->addSelect('p.latitude as latitude')
            ->addSelect('p.longitude as longitude')
            ->addSelect('companyObject.companyId as companyId')
            ->addSelect('companyObject.id as companyObjectId')
            ->leftJoin('p.companyObject', 'companyObject')
            ->where('p.id in (:ids)')
            ->setParameter(':ids', $ids)
            ->getQuery();
    }
}
