<?php

namespace ITDoors\HaccpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PointGroupCharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointGroupCharacteristicRepository extends EntityRepository
{
    /**
     * Returns Characteristics by GroupId
     *
     * @param int $groupId
     *
     * @return Query
     */
    public function getCharacteristicsQueryByGroupId($groupId)
    {
        return $this->createQueryBuilder('pgc')
            ->select('pgc')
            ->where('pgc.groupId = :groupId')
            ->setParameter(':groupId', $groupId)
            ->getQuery();
    }

    /**
     * Returns data for backup
     *
     * @return array
     */
    public function getBackupData()
    {
        return $this->createQueryBuilder('obj')
            ->getQuery()
            ->getArrayResult();
    }
}
