<?php

namespace ITDoors\HaccpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PointGroupCharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointGroupCharacteristicRepository extends EntityRepository
{
    /**
     * Returns Characteristics by GroupId
     *
     * @param int $groupId
     *
     * @return Query
     */
    public function getCharacteristicsQueryByGroupId($groupId)
    {
        return $this->createQueryBuilder('pgc')
            ->select('pgc')
            ->where('pgc.groupId = :groupId')
            ->setParameter(':groupId', $groupId)
            ->getQuery();
    }

    /**
     * Returns data for backup
     *
     * @return array
     */
    public function getBackupData()
    {
        return $this->createQueryBuilder('obj')
            ->select('obj.id as id')
            ->addSelect('obj.name as name')
            ->addSelect('obj.groupId as point_group_id')
            ->addSelect('obj.description as description')
            ->addSelect('obj.unit as unit')
            ->addSelect('obj.dataType as data_type')
            ->addSelect('obj.allowValueMax as allow_value_max')
            ->addSelect('obj.allowValueMin as allow_value_min')
            ->addSelect('obj.criticalValueTop as critical_value_top')
            ->addSelect('obj.criticalValueBottom as critical_value_bottom')
            ->addSelect('obj.criticalColorTop as critical_color_top')
            ->addSelect('obj.criticalColorBottom as critical_color_bottom')
            ->addSelect('obj.criticalColorMiddle as critical_color_middle')
            ->addSelect('obj.inputType as input_type')
            ->getQuery()
            ->getArrayResult();
    }
}
