<?php

namespace ITDoors\HaccpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PointStatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointStatisticsRepository extends EntityRepository
{
    /**
     * @var int
     */
    protected $baseStatisticsLimit;

    /**
     * Returns point statistics Query depending on options
     *
     * @param mixed[] $options
     *
     * @return Query
     */
    public function getStatisticsQuery($options)
    {
        $sql = $this->createQueryBuilder('ps')
            ->select('ps.id as id')
            ->addSelect('ps.value as value')
            ->addSelect('ps.entryDate as entryDate')
            ->addSelect('characteristic.id as characteristicId')
            ->addSelect('characteristic.name as characteristicName')
            ->addSelect('characteristic.unit as characteristicUnit')
            ->addSelect('characteristic.criticalValueTop as criticalValueTop')
            ->addSelect('characteristic.criticalValueBottom as criticalValueBottom')
            ->leftJoin('ps.characteristic', 'characteristic');

        // Start date
        if (isset($options['startDate']) && $options['startDate']) {
            $sql
                ->andWhere('ps.entryDate >= :startDate')
                ->setParameter(':startDate', $options['startDate']);
        }

        // End date
        if (isset($options['endDate']) && $options['endDate']) {
            $sql
                ->andWhere('ps.entryDate <= :endDate')
                ->setParameter(':endDate', $options['endDate']);
        }

        // Specific statistic Ids
        if (isset($options['statisticsIds']) && sizeof($options['statisticsIds'])) {
            $sql
                ->andWhere('ps.id in (:statisticsIds)')
                ->setParameter(':statisticsIds', $options['statisticsIds']);
        }

        // Point Ids
        if (isset($options['pointIds']) && is_array($options['pointIds'])) {
            $sql
                ->andWhere('ps.pointId in (:pointIds)')
                ->setParameter(':pointIds', $options['pointIds']);
        }

        if (isset($options['limit']) && $options['limit']) {
            $sql
                ->setMaxResults($options['limit']);
        }

        if (isset($options['lastStatisticId']) && $options['lastStatisticId']) {
            $sql
                ->andWhere('ps.id < :lastStatisticId')
                ->setParameter(':lastStatisticId', $options['lastStatisticId']);
        }

        $sql
            ->orderBy('ps.entryDate', 'DESC')
            ->addOrderBy('ps.id', 'DESC');

        return $sql->getQuery();
    }

    /**
     * Returns point statistics depending on options
     *
     * @param mixed[] $options
     *
     * @return mixed[]
     */
    public function getStatistics($options)
    {
        $query = $this->getStatisticsQuery($options);

        return $query->getResult();
    }
}
