# PLAN
plan_show:
    pattern:  /plan/show/{planId}
    defaults: { _controller: ITDoorsHaccpBundle:Plan:show }

plan_map:
    pattern:  /plan/map/{planId}
    defaults: { _controller: ITDoorsHaccpBundle:Plan:map }

# POINT
point_show_ajax:
    pattern:  /ajax/point/{id}
    defaults: { _controller: ITDoorsHaccpBundle:Point:showAjax }

point_statistics_show_ajax:
    pattern:  /ajax/point/{id}/statistics
    defaults: { _controller: ITDoorsHaccpBundle:Point:statisticsAjax }

# CONTOUR
contour_choices_ajax:
    pattern:  /ajax/contour/choices
    defaults: { _controller: ITDoorsHaccpBundle:Contour:choicesAjax }

contour_choices_by_ids_ajax:
    pattern:  /ajax/contour/choices/ids
    defaults: { _controller: ITDoorsHaccpBundle:Contour:choicesByIdsAjax }

# COMPANY OBJECT
company_object_infestation:
    pattern:  /company_object/infestation
    defaults: { _controller: ITDoorsHaccpBundle:CompanyObject:infestation }

company_object_infestation_content:
    pattern:  /company_object/infestation_content
    defaults: { _controller: ITDoorsHaccpBundle:CompanyObject:infestationContent }
