plan_show:
    pattern:  /plan/show/{planId}.html
    defaults: { _controller: ITDoorsHaccpBundle:Plan:show }

plan_map:
    pattern:  /plan/map/{planId}.html
    defaults: { _controller: ITDoorsHaccpBundle:Plan:map }
#POINT ROUTE
point_show_ajax:
    pattern:  /ajax/point/show/{id}.html
    defaults: { _controller: ITDoorsHaccpBundle:Point:showAjax }
