imports:
    - { resource: "services/point.yml" }
    - { resource: "services/company.yml" }
    - { resource: "services/company_object.yml" }
    - { resource: "services/plan.yml" }
    - { resource: "services/point_group.yml" }
    - { resource: "services/point_statistics.yml" }
    - { resource: "services/point_status.yml" }
    - { resource: "services/point_group_characteristic.yml" }
    - { resource: "services/contour.yml" }
    - { resource: "services/service.yml" }

parameters:
    # Filtes & Forms
    it_doors_haccp.form.serviceFilterType.class: ITDoors\HaccpBundle\Form\ServiceFilterType
    it_doors_haccp.form.pointStatisticsDateRangeType.class: ITDoors\HaccpBundle\Form\PointStatisticsDateRangeType

    # Log
    it_doors_haccp.log.service.class: ITDoors\HaccpBundle\Services\LogService

#API V1 SERVICE CLASSES
    it_doors_haccp.point.api.v1.service.class: ITDoors\HaccpBundle\Services\PointApiV1Service

    it_doors_haccp.point.statistics.api.v1.service.class: ITDoors\HaccpBundle\Services\PointStatisticsApiV1Service

    it_doors_haccp.point.status.api.v1.service.class: ITDoors\HaccpBundle\Services\PointStatusApiV1Service

    it_doors_haccp.point.group.api.v1.service.class: ITDoors\HaccpBundle\Services\PointGroupApiV1Service

    it_doors_haccp.form.pointStatisticsApiForm.class: ITDoors\HaccpBundle\Form\PointStatisticsApiForm

    it_doors_haccp.form.pointStatisticsType.class: ITDoors\HaccpBundle\Form\PointStatisticsType

services:
    it_doors_haccp.twig.point_extension:
        class: ITDoors\HaccpBundle\Twig\PointExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    it_doors_haccp.form.serviceFilterType:
        class: %it_doors_haccp.form.serviceFilterType.class%
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: serviceFilterType }

    it_doors_haccp.form.pointStatisticsDateRangeType:
        class: %it_doors_haccp.form.pointStatisticsDateRangeType.class%
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: pointStatisticsDateRangeType }

    it_doors_haccp.form.pointStatisticsType:
        class: %it_doors_haccp.form.pointStatisticsType.class%
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: pointStatisticsType }

#API SERVICES V1
    it_doors_haccp.point.api.v1.service:
        class: %it_doors_haccp.point.api.v1.service.class%
        arguments: [ @it_doors_haccp.point.repository, @point.statistics.api.v1.service ]

    point.api.v1.service:
        alias: it_doors_haccp.point.api.v1.service

    it_doors_haccp.point.statistics.api.v1.service:
        class: %it_doors_haccp.point.statistics.api.v1.service.class%
        arguments: [ @service_container, @it_doors_haccp.point.statistics.repository, %api.v1.point.statistics.limit% ]

    point.statistics.api.v1.service:
        alias: it_doors_haccp.point.statistics.api.v1.service

    it_doors_haccp.point.status.api.v1.service:
        class: %it_doors_haccp.point.status.api.v1.service.class%
        arguments: [ @service_container ]

    point.status.api.v1.service:
        alias: it_doors_haccp.point.status.api.v1.service

    it_doors_haccp.form.pointStatisticsApiType:
        class: %it_doors_haccp.form.pointStatisticsApiForm.class%
        tags:
            - { name: form.type, alias: pointStatisticsApiForm }

    it_doors_haccp.point.group.api.v1.service:
        class: %it_doors_haccp.point.group.api.v1.service.class%
        arguments: [ @service_container ]

    point.group.api.v1.service:
        alias: it_doors_haccp.point.group.api.v1.service

    it_doors_haccp.log.service:
        class: %it_doors_haccp.log.service.class%
        arguments: [ @service_container ]

    log.service:
        alias: it_doors_haccp.log.service
