<?php

namespace ITDoors\LookupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LookupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LookupRepository extends EntityRepository
{
}
