<?php

namespace ITDoors\HaccpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends EntityRepository
{
    /**
     * Returns query for show
     *
     * @param int[] $ids
     *
     * @return Query
     */
    public function getForShowQuery($ids)
    {
        return $this->createQueryBuilder('p')
            ->select('p.id as id')
            ->addSelect('p.name as name')
            ->addSelect('p.imageSrc as imageSrc')
            ->addSelect('p.imageWidth as imageWidth')
            ->addSelect('p.imageHeight as imageHeight')
            ->addSelect('p.type as type')
            ->addSelect('p.latitude as latitude')
            ->addSelect('p.longitude as longitude')
            ->addSelect('p.maxZoom as maxZoom')
            ->addSelect('parent.id as parentId')
            ->addSelect('parent.name as parentName')
            ->addSelect('companyObject.companyId as companyId')
            ->addSelect('companyObject.id as companyObjectId')
            ->leftJoin('p.companyObject', 'companyObject')
            ->leftJoin('p.parent', 'parent')
            ->where('p.id in (:ids)')
            ->setParameter(':ids', $ids)
            ->getQuery();
    }

    /**
     * Get Children Query
     *
     * @params int[] $parentIds
     */
    public function getChildrenQuery($parentIds)
    {
        return $this->createQueryBuilder('p')
            ->select('p.id as id')
            ->addSelect('p.name as name')
            ->addSelect('p.type as type')
            ->addSelect('p.parentLatitudeTopLeft as parentLatitudeTopLeft')
            ->addSelect('p.parentLongitudeTopLeft as parentLongitudeTopLeft')
            ->addSelect('p.parentLatitudeBottomRight as parentLatitudeBottomRight')
            ->addSelect('p.parentLongitudeBottomRight as parentLongitudeBottomRight')
            ->where('p.parentId in (:parentIds)')
            ->setParameter(':parentIds', $parentIds)
            ->getQuery();
    }
}
