<?php

namespace ITDoors\HaccpBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PointStatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointStatisticsRepository extends EntityRepository
{
    /**
     * @var int
     */
    protected $baseStatisticsLimit;

    /**
     * Returns point statistics Query depending on options
     *
     * @param mixed[] $options
     *
     * @return Query
     */
    //public function getStatisticsQuery($ids, $limit = 10, $startDate = null, $endDate = null, $statisticsIds = array())
    public function getStatisticsQuery($options)
    {
        $sql = $this->createQueryBuilder('ps')
            ->select('ps.id as id')
            ->addSelect('ps.value as value')
            ->addSelect('ps.entryDate as entryDate')
            ->addSelect('Characteristic.id as characteristicId')
            ->addSelect('Characteristic.name as characteristicName')
            ->addSelect('Characteristic.unit as characteristicUnit')
            ->addSelect('Characteristic.criticalValueTop as criticalValueTop')
            ->addSelect('Characteristic.criticalValueBottom as criticalValueBottom')
            ->leftJoin('ps.Characteristic', 'Characteristic');

        // Start date
        if (isset($options['startDate']) && $options['startDate']) {
            $sql
                ->andWhere('ps.entryDate >= :startDate')
                ->setParameter(':startDate', $options['startDate']);
        }

        // End date
        if (isset($options['endDate']) && $options['endDate']) {
            $sql
                ->andWhere('ps.entryDate <= :endDate')
                ->setParameter(':endDate', $options['endDate']);
        }

        // Specific statistic Ids
        if (isset($options['statisticsIds']) && sizeof($options['statisticsIds'])) {
            $sql
                ->andWhere('ps.id in (:statisticsIds)')
                ->setParameter(':statisticsIds', $options['statisticsIds']);
        }

        // Point Ids
        if (isset($options['pointIds']) && is_array($options['pointIds'])) {
            $sql
                ->andWhere('ps.pointId in (:pointIds)')
                ->setParameter(':pointIds', $options['pointIds']);
        }

        if (isset($options['limit']) && $options['limit']) {
            $sql
                ->setMaxResults($options['limit']);
        }

        if (isset($options['lastStatisticId']) && $options['lastStatisticId']) {
            $sql
                ->andWhere('ps.id < :lastStatisticId')
                ->setParameter(':lastStatisticId', $options['lastStatisticId']);
        }

        $sql
            ->orderBy('ps.entryDate', 'DESC')
            ->addOrderBy('ps.id', 'DESC');

        return $sql->getQuery();
    }

    /**
     * Returns point statistics depending on options
     *
     * @param mixed[] $options
     *
     * @return mixed[]
     */
    public function getStatistics($options)
    {
        $query = $this->getStatisticsQuery($options);

        return $query->getResult();
    }
}
