parameters:
    # Point Group
    it_doors_haccp.point.group.repository.class: ITDoors\HaccpBundle\Entity\PointGroupRepository
    it_doors_haccp.point.group.repository.entity: ITDoors\HaccpBundle\Entity\PointGroup
    it_doors_haccp.point.group.service.class: ITDoors\HaccpBundle\Services\PointGroupService

services:
    # Point
    it_doors_haccp.point.group.repository:
        class: %it_doors_haccp.point.group.repository.class%
        factory_service: doctrine # this is an instance of Registry
        factory_method: getRepository
        arguments: [ %it_doors_haccp.point.group.repository.entity% ]

    point.group.repository:
        alias: it_doors_haccp.point.repository

    it_doors_haccp.point.group.service:
        class: %it_doors_haccp.point.group.service.class%
        arguments: [ @it_doors_haccp.point.group.repository, @service_container]

    point.group.service:
        alias: it_doors_haccp.point.group.service
    # Point END