parameters:
    # Point Status
    it_doors_haccp.point.status.repository.class: ITDoors\HaccpBundle\Entity\PointStatusRepository
    it_doors_haccp.point.status.repository.entity: ITDoors\HaccpBundle\Entity\PointStatus
    it_doors_haccp.point.status.service.class: ITDoors\HaccpBundle\Services\PointStatusService

services:
    # Point Status
    it_doors_haccp.point.status.repository:
        class: %it_doors_haccp.point.status.repository.class%
        factory_service: doctrine # this is an instance of Registry
        factory_method: getRepository
        arguments: [ %it_doors_haccp.point.status.repository.entity% ]

    point.status.repository:
        alias: it_doors_haccp.point.status.repository

    it_doors_haccp.point.status.service:
        class: %it_doors_haccp.point.status.service.class%
        arguments: [ @it_doors_haccp.point.status.repository, @service_container]

    point.status.service:
        alias: it_doors_haccp.point.status.service
    # Point Status END