parameters:
    # Point Group Characteristic
    it_doors_haccp.point.group.characteristic.repository.class: ITDoors\HaccpBundle\Entity\PointGroupCharacteristicRepository
    it_doors_haccp.point.group.characteristic.repository.entity: ITDoors\HaccpBundle\Entity\PointGroupCharacteristic
    it_doors_haccp.point.group.characteristic.service.class: ITDoors\HaccpBundle\Services\PointGroupCharacteristicService

services:
    # Point Group Characteristic
    it_doors_haccp.point.group.characteristic.repository:
        class: %it_doors_haccp.point.group.characteristic.repository.class%
        factory_service: doctrine # this is an instance of Registry
        factory_method: getRepository
        arguments: [ %it_doors_haccp.point.group.characteristic.repository.entity% ]

    point.group.characteristic.repository:
        alias: it_doors_haccp.point.group.characteristic.repository

    it_doors_haccp.point.group.characteristic.service:
        class: %it_doors_haccp.point.group.characteristic.service.class%
        arguments: [ @it_doors_haccp.point.group.characteristic.repository, @service_container]

    point.characteristic.service:
        alias: it_doors_haccp.point.group.characteristic.service
    # Point Group Characteristic END