it_doors_lookup:
    resource: "@ITDoorsLookupBundle/Resources/config/routing.yml"
    prefix:   /

it_doors_rest:
    resource: "@ITDoorsRestBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api

it_doors_ajax:
    resource: "@ITDoorsAjaxBundle/Resources/config/routing.yml"
    prefix:   /

it_doors_dashboard:
    resource: "@ITDoorsDashboardBundle/Resources/config/routing.yml"
    prefix:   /

it_doors_haccp:
    resource: "@ITDoorsHaccpBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

