ITDoors\LookupBundle\Entity\Lookup:
    type: entity
    table: lookup
    repositoryClass: ITDoors\LookupBundle\Entity\LookupRepository
    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }
    fields:
        name:
            type: string
            length: 255
            nullable: false
        key:
            type: string
            length: 255
            nullable: false
        groupName:
            type: string
            length: 255
            nullable: true
            column: group_name
        value:
            type: string
            length: 255
            nullable: true
