parameters:
#    it_doors_lookup.example.class: ITDoors\LookupBundle\Example

services:
#    it_doors_lookup.example:
#        class: %it_doors_lookup.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
