parameters:
#    it_doors_rest.example.class: ITDoors\RestBundle\Example

services:
#    it_doors_rest.example:
#        class: %it_doors_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
