parameters:
    it_doors_rest.api_doc.extractor.array_collection_parser.class: ITDoors\RestBundle\Parser\ApiDocOutputArray

services:
    it_doors_rest.api_doc.extractor.array_collection_parser:
        class: %it_doors_rest.api_doc.extractor.array_collection_parser.class%
        arguments: ['@nelmio_api_doc.parser.jms_metadata_parser']
        tags:
            - { name: nelmio_api_doc.extractor.parser, priority: 2 }
