ITDoors\HaccpBundle\Entity\PointGroupCharacteristic:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            exclude: true
            groups: [api, apiFull]
            since_version: 1.0
            until_version: 1.0
        name:
            type: string
            exclude: true
            groups: [api, apiFull]
            since_version: 1.0
            until_version: 1.0
        unit:
            type: string
            exclude: true
            groups: [api, apiFull]
            since_version: 1.0
            until_version: 1.0
        dataType:
            type: string
            exclude: true
            groups: [apiFull]
            since_version: 1.0
            until_version: 1.0
            serialized_name: dataType
        inputType:
            type: string
            exclude: true
            groups: [apiFull]
            since_version: 1.0
            until_version: 1.0
            serialized_name: inputType
        criticalValueBottom:
            type: string
            exclude: true
            groups: [api, apiFull]
            since_version: 1.0
            until_version: 1.0
            serialized_name: criticalValueBottom
        criticalValueTop:
            type: string
            exclude: true
            groups: [api, apiFull]
            since_version: 1.0
            until_version: 1.0
            serialized_name: criticalValueTop
        allowValueMax:
            type: string
            exclude: true
            groups: [apiFull]
            since_version: 1.0
            until_version: 1.0
            serialized_name: allowValueMax
        allowValueMin:
            type: string
            exclude: true
            groups: [apiFull]
            since_version: 1.0
            until_version: 1.0
            serialized_name: allowValueMin
