ITDoors\HaccpBundle\Entity\CompanyObject:
  type: entity
  repositoryClass: ITDoors\HaccpBundle\Entity\CompanyObjectRepository
  table: company_object
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 50
      nullable: false
    companyId:
      type: integer
      column: company_id
  manyToOne:
    company:
      targetEntity: Company
      joinColumn:
        name: company_id
        referencedColumnName: id