ITDoors\HaccpBundle\Entity\Company:
  type: entity
  repositoryClass: ITDoors\HaccpBundle\Entity\CompanyRepository
  table: company
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 50