ITDoors\HaccpBundle\Entity\Plan:
  type: entity
  repositoryClass: ITDoors\HaccpBundle\Entity\PlanRepository
  table: plan
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 50
    imageSrc:
      type: string
      length: 50
      column: image_src
      nullable: true
    imageWidth:
      type: integer
      column: image_width
      nullable: true
    imageHeight:
      type: integer
      column: image_height
      nullable: true
    latitude:
      type: string
      length: 50
      nullable: true
    longitude:
      type: string
      length: 50
      nullable: true
    companyObjectId:
      type: integer
      column: company_object_id
    type:
      type: string
      length: 20
      nullable: true
    parentId:
      type: integer
      nullable: true
      column: parent_id
    maxZoom:
      type: integer
      nullable: true
      column: max_zoom
  oneToMany:
    children:
      targetEntity: Plan
      mappedBy: parent
  manyToOne:
    companyObject:
      targetEntity: CompanyObject
      joinColumn:
        name: company_object_id
        referencedColumnName: id
    parent:
      targetEntity: Plan
      inversedBy: children