ITDoors\HaccpBundle\Entity\PointGroup:
  type: entity
  repositoryClass: ITDoors\HaccpBundle\Entity\PointGroupRepository
  table: point_group
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      length: 50